Testimonials grid section adufe obanijesu
hackers-ignite-open-source-community/FrontendMentor pull request #21
Opened 2023-10-22 23:45 UTC by Adufe-Obanijesu

Done with the testimonials grid section challenge using Vite, React and TailwindCSS
![thumbnail](https://github.com/hackers-ignite-open-source-community/FrontendMentor/assets/50187465/a263148a-918e-4731-9226-d455231eb336)

2023-10-25 11:57 UTC, PhantomOz approved these changes

2023-10-25 12:04 UTC, PhantomOz requested changes
Add to the contributors.md file

2023-10-26 00:25 UTC, Adufe-Obanijesu commented
I have updated the contributors.md file sir

2023-10-26 07:22 UTC, PhantomOz approved these changes

2023-10-26 07:22 UTC, merged