add: result summary component solution
hackers-ignite-open-source-community/FrontendMentor pull request #7
Opened 2023-10-07 16:27 UTC by bishwobista

2023-10-07 18:27 UTC, PhantomOz reviewed
Please add your name to the contributors.md

2023-10-07 19:12 UTC, PhantomOz requested changes
Add your name to the contributors.md

2023-10-08 00:53 UTC, bishwobista commented
I submitted another pull request.

2023-10-08 21:23 UTC, PhantomOz approved these changes

2023-10-08 21:23 UTC, merged